const { Pool } = require('pg');
const pool = new Pool({
  connectionString: 'postgres://agencia_user:soX0Y3npFDhyRtISsjBFrwBxfAIo1kB5bzuBwZzu3RVLiz0kfg3H8Dm5GHTt39pN@195.200.7.184:54320/agencia_eua',
  ssl: false
});

const leads = [
  { response_id:'hu2ohzugj93h1j6v2oj4rhu2ohzeoy8j', first_name:'Camilo', last_name:'Alonso', phone:'+16896105537', email:'ampusaservices@gmail.com', empresa:'Gold property care', tipo_negocio:'Serviços de Limpeza (Cleaning)', tempo_negocio:'5 a 8 anos', num_colaboradores:'2 a 3 pessoas', faturamento_anual:'$250.000 a $500.000', visibilidade_google:'Não sei / Nunca verifiquei', tem_gmb:'Acho que sim, mas nunca verifiquei', usa_instagram:'Tenho perfil mas não posto nada', instagram_handle:null, tem_site:'Sim, mas está desatualizado ou parado', url_site:'Goldpropertycare.com', investimento_mensal:'Menos de $300', faz_anuncios:'Já tentei, mas não tive resultado', controle_clientes:'Uso planilha (Excel/Google Sheets)', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Já ouvi falar mas nunca usei', dor_sem_clientes:true, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:true, problema_principal:'Leads qualificados e vendas', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Planejando — Vou investir nos próximos 2-3 meses', intencao_avancar:false, intencao_entender:true, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-04-30 19:11:18 UTC', stage_date:null, submit_date:'2026-04-30 19:14:19 UTC', network_id:'e97a1f42da' },
  { response_id:'rsrqld5njdzuvznw6rsrqzzy5kmbl2vo', first_name:'Ramon', last_name:'Dos Santos', phone:'+19787282691', email:'carpentryrs123@gmail.com', empresa:null, tipo_negocio:null, tempo_negocio:null, num_colaboradores:null, faturamento_anual:null, visibilidade_google:null, tem_gmb:null, usa_instagram:null, instagram_handle:null, tem_site:null, url_site:null, investimento_mensal:null, faz_anuncios:null, controle_clientes:null, canal_aquisicao:null, usa_ia:null, dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:null, trabalhou_agencia:null, urgencia:null, intencao_avancar:false, intencao_entender:false, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'partial', start_date:'2026-04-30 15:11:11 UTC', stage_date:'2026-04-30 15:11:37 UTC', submit_date:null, network_id:'e97a1f42da' },
  { response_id:'jj3qwxshwv8veweijj3qnezvpbg5skut', first_name:'Barbara', last_name:'Nogueira', phone:'+17867403155', email:'barbaradesouza@icloud.com', empresa:'All Star Concept Salon', tipo_negocio:'Salão de Beleza / Estética', tempo_negocio:'Menos de 1 ano', num_colaboradores:'11 a 20 pessoas', faturamento_anual:'$500.000 a $1.000.000', visibilidade_google:'Não sei / Nunca verifiquei', tem_gmb:'Sim, mas não sei mexer direito', usa_instagram:'Sim, tenho um perfil da empresa', instagram_handle:'@allstarconcept', tem_site:'Estou criando/planejando criar', url_site:null, investimento_mensal:'$300 a $1.000', faz_anuncios:'Sim, invisto nos dois (Facebook e Google)', controle_clientes:'Em construção', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Sim, uso IA para criar posts, textos ou conteúdo', dor_sem_clientes:true, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:'Melhoras as venda e posicionamento', trabalhou_agencia:'Sim, e tive bons resultados', urgencia:'Estou só conhecendo as opções por enquanto', intencao_avancar:false, intencao_entender:false, intencao_talvez:false, intencao_sem_orcamento:true, intencao_pensar:false, response_type:'completed', start_date:'2026-04-30 15:10:56 UTC', stage_date:null, submit_date:'2026-04-30 15:20:52 UTC', network_id:'3f4b2561a1' },
  { response_id:'p7rzp7ccjfgmajasso5ojp7rzp72a6nr', first_name:'Mayara', last_name:'Ciolfi', phone:'+19044023414', email:'mciolfirealtor@gmail.com', empresa:'Mayara Ciolfi', tipo_negocio:'Imóveis / Real Estate', tempo_negocio:'1 a 3 anos', num_colaboradores:'Só eu (sozinho)', faturamento_anual:'$100.000 a $250.000', visibilidade_google:'Sim, mas as informações estão desatualizadas', tem_gmb:'Acho que sim, mas nunca verifiquei', usa_instagram:'Sim, uso minha rede pessoal (perfil pessoal)', instagram_handle:'mayaraciolfi', tem_site:'Sim, mas está desatualizado ou parado', url_site:null, investimento_mensal:'$300 a $1.000', faz_anuncios:'Nunca fiz / Não sei como fazer', controle_clientes:'Uso planilha (Excel/Google Sheets)', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Sim, uso IA para criar posts, textos ou conteúdo', dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:true, problema_principal:'Intencionalidade e conversao', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Planejando — Vou investir nos próximos 2-3 meses', intencao_avancar:false, intencao_entender:false, intencao_talvez:true, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-04-30 15:10:44 UTC', stage_date:null, submit_date:'2026-04-30 15:15:58 UTC', network_id:'bdcf2afe97' },
  { response_id:'q8mfy40aa706kzrvtq8mfygcsla83zu7', first_name:'Brena', last_name:'Lopes', phone:'+14074737149', email:'brena_franca@hotmail.com', empresa:'Miniboss', tipo_negocio:'Salão de Beleza / Estética', tempo_negocio:'+ 10 anos', num_colaboradores:'Mais de 20 pessoas', faturamento_anual:'$500.000 a $1.000.000', visibilidade_google:'Não apareço', tem_gmb:'Não tenho', usa_instagram:'Sim, tenho um perfil da empresa', instagram_handle:'@miniboss', tem_site:'Sim, tenho site ativo', url_site:'Www.miniboss.com', investimento_mensal:'$0 (não invisto nada)', faz_anuncios:'Nunca fiz / Não sei como fazer', controle_clientes:'Uso um CRM (sistema de gestão)', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Sim, uso IA para criar posts, textos ou conteúdo', dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:true, dor_dependencia_op:false, problema_principal:'Instagram', trabalhou_agencia:'Não, essa seria a primeira vez', urgencia:'Estou só conhecendo as opções por enquanto', intencao_avancar:false, intencao_entender:false, intencao_talvez:false, intencao_sem_orcamento:true, intencao_pensar:true, response_type:'completed', start_date:'2026-04-30 15:10:38 UTC', stage_date:null, submit_date:'2026-04-30 15:17:11 UTC', network_id:'bbbd8d9a05' },
  { response_id:'2ymf4uv1l52wnmhhqv2ymfqjvi0f4e9y', first_name:'Barbhara', last_name:'Nunes', phone:'+14076692950', email:'barbharausa@gmail.com', empresa:'B2You Insurance', tipo_negocio:'Seguros (Insurance)', tempo_negocio:'1 a 3 anos', num_colaboradores:'4 a 10 pessoas', faturamento_anual:'Menos de $100.000', visibilidade_google:'Não apareço', tem_gmb:'Não tenho', usa_instagram:'Tenho perfil mas não posto nada', instagram_handle:'@b2you.insurance', tem_site:'Sim, tenho site ativo', url_site:'Www.b2youinsurance.com', investimento_mensal:'$0 (não invisto nada)', faz_anuncios:'Nunca fiz / Não sei como fazer', controle_clientes:'Uso um CRM (sistema de gestão)', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Sim, uso chatbot ou atendimento automatizado', dor_sem_clientes:true, dor_so_brasileiro:false, dor_sem_google:true, dor_sem_mkt:true, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:'Preciso me posicionar na rede social e crescermos no mercado brasileiro', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Urgente — Preciso começar agora', intencao_avancar:false, intencao_entender:true, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-04-30 15:10:34 UTC', stage_date:null, submit_date:'2026-04-30 15:19:01 UTC', network_id:'e97a1f42da' },
  { response_id:'2l18fuzuaj5ymxj2jl2l18fxkyj11yml', first_name:'Fernando', last_name:'Rodrigues', phone:'+14073678330', email:'nandorodrigues73@gmail.com', empresa:'Dream Team - Life Planner', tipo_negocio:'Planejamento Financeiro', tempo_negocio:'5 a 8 anos', num_colaboradores:'2 a 3 pessoas', faturamento_anual:'$1.000.000 a $5.000.000', visibilidade_google:'Não apareço', tem_gmb:'Sim, mas não sei mexer direito', usa_instagram:'Sim, uso minha rede pessoal (perfil pessoal)', instagram_handle:'@fernandorodriguesusa', tem_site:'Sim, tenho site ativo', url_site:'Perfil financeiro.com', investimento_mensal:'$300 a $1.000', faz_anuncios:'Sim, invisto apenas no Facebook/Instagram', controle_clientes:'Uso um CRM (sistema de gestão)', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Sim, uso IA para organizar agenda ou tarefas', dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:true, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:'Funil de vendas automatizado', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Alta prioridade — Quero começar nas próximas semanas', intencao_avancar:true, intencao_entender:false, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-04-30 15:10:34 UTC', stage_date:null, submit_date:'2026-04-30 15:22:19 UTC', network_id:'c907d044c4' },
  { response_id:'qpsu12ivyit92bqbpuvoukn0qpsu12ia', first_name:'Pedro', last_name:'Vitor', phone:'+18569053653', email:'pedrovitorusa@gmail.com', empresa:'Don Pedro Meats & Market inc', tipo_negocio:'Restaurante / Food Service', tempo_negocio:'+ 10 anos', num_colaboradores:'Mais de 20 pessoas', faturamento_anual:'+$5.000.000', visibilidade_google:'Sim, apareço com endereço, telefone e avaliações', tem_gmb:'Não sei o que é isso', usa_instagram:'Sim, tenho um perfil da empresa', instagram_handle:'donpedromeatsoficial', tem_site:'Estou criando/planejando criar', url_site:null, investimento_mensal:'$300 a $1.000', faz_anuncios:'Sim, invisto apenas no Facebook/Instagram', controle_clientes:'Guardo tudo na cabeça / Não tenho controle', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Não uso nada de IA ainda', dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:true, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:'Encontrar a agência certa', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Urgente — Preciso começar agora', intencao_avancar:false, intencao_entender:true, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-04-30 15:10:29 UTC', stage_date:null, submit_date:'2026-04-30 15:17:30 UTC', network_id:'031d751981' },
  { response_id:'qx8h0dl2wzy0pmnfezgqx8h9th6gv2ko', first_name:'Luis Thiago', last_name:'Vieira', phone:'+14254491022', email:'info@twinklecs.com', empresa:'Twinkle Cleaning Services LLC', tipo_negocio:'Serviços de Limpeza (Cleaning)', tempo_negocio:'+ 10 anos', num_colaboradores:'11 a 20 pessoas', faturamento_anual:'$500.000 a $1.000.000', visibilidade_google:'Sim, apareço com endereço, telefone e avaliações', tem_gmb:'Sim, e eu gerencio ele ativamente', usa_instagram:'Tenho perfil mas não posto nada', instagram_handle:'@twinklecleaningservices', tem_site:'Sim, tenho site ativo', url_site:'Twinklecs.com', investimento_mensal:'$1.000 a $3.000', faz_anuncios:'Sim, invisto apenas no Google', controle_clientes:'Uso um CRM (sistema de gestão)', canal_aquisicao:'Google / Busca orgânica', usa_ia:'Sim, uso IA para responder clientes ou e-mails', dor_sem_clientes:true, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:true, dor_dependencia_op:false, problema_principal:'Redes sociais', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Planejando — Vou investir nos próximos 2-3 meses', intencao_avancar:false, intencao_entender:true, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-04-30 15:10:28 UTC', stage_date:null, submit_date:'2026-04-30 15:24:08 UTC', network_id:'f75513b697' },
  { response_id:'pon7ssno7mmz2qqh4wwh25pon7s63wtq', first_name:'Alejandra', last_name:'Lopez', phone:'+14076019509', email:'alejandra@aesaccounting.net', empresa:null, tipo_negocio:null, tempo_negocio:null, num_colaboradores:null, faturamento_anual:null, visibilidade_google:null, tem_gmb:null, usa_instagram:null, instagram_handle:null, tem_site:null, url_site:null, investimento_mensal:null, faz_anuncios:null, controle_clientes:null, canal_aquisicao:null, usa_ia:null, dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:null, trabalhou_agencia:null, urgencia:null, intencao_avancar:false, intencao_entender:false, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'partial', start_date:'2026-04-30 15:10:25 UTC', stage_date:'2026-04-30 15:11:10 UTC', submit_date:null, network_id:'eb66b7c540' },
  { response_id:'88ej3ptdr4su5rvuxaz8888ej3pt6940', first_name:'Patricia', last_name:'Lobo', phone:'+13217046158', email:'patricialobo76@yahoo.com.br', empresa:'La ruta pupuseria', tipo_negocio:'Restaurante / Food Service', tempo_negocio:'1 a 3 anos', num_colaboradores:'2 a 3 pessoas', faturamento_anual:'Menos de $100.000', visibilidade_google:'Sim, apareço com endereço, telefone e avaliações', tem_gmb:'Não tenho', usa_instagram:'Sim, tenho um perfil da empresa', instagram_handle:'La ruta pupuseria', tem_site:'Não tenho site', url_site:null, investimento_mensal:'Menos de $300', faz_anuncios:'Já tentei, mas não tive resultado', controle_clientes:'Anoto em caderno ou agenda', canal_aquisicao:'Redes sociais (Instagram, TikTok)', usa_ia:'Sim, uso chatbot ou atendimento automatizado', dor_sem_clientes:true, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:'Ter mais resultados', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Urgente — Preciso começar agora', intencao_avancar:false, intencao_entender:true, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-02-21 18:10:54 UTC', stage_date:null, submit_date:'2026-02-21 18:16:48 UTC', network_id:'d05583f6b1' },
  { response_id:'13xh44q9kwn78br9s13t4ldatmngm2vk', first_name:'Erika', last_name:'Figueiredo', phone:'+16893322987', email:'erikarfig@hotmail.com', empresa:'Erika Figueiredo Real Estate', tipo_negocio:'Imóveis / Real Estate', tempo_negocio:'Menos de 1 ano', num_colaboradores:'Só eu (sozinho)', faturamento_anual:'$100.000 a $250.000', visibilidade_google:'Não apareço', tem_gmb:'Não tenho', usa_instagram:'Sim, uso minha rede pessoal (perfil pessoal)', instagram_handle:null, tem_site:'Não tenho site', url_site:null, investimento_mensal:'Menos de $300', faz_anuncios:'Nunca fiz / Não sei como fazer', controle_clientes:'Anoto em caderno ou agenda', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Já ouvi falar mas nunca usei', dor_sem_clientes:true, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:'Resultado', trabalhou_agencia:'Não, essa seria a primeira vez', urgencia:'Urgente — Preciso começar agora', intencao_avancar:false, intencao_entender:false, intencao_talvez:true, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-02-20 22:06:31 UTC', stage_date:null, submit_date:'2026-02-20 22:10:11 UTC', network_id:'e97a1f42da' },
  { response_id:'xor8bm43bidnnxo6v2jbv1mk7kaa8zgu', first_name:'Wagner', last_name:'Correa', phone:'+19046992517', email:'wagnercapacete@gmail.com', empresa:'Pastor', tipo_negocio:'Igreja', tempo_negocio:'+ 10 anos', num_colaboradores:'2 a 3 pessoas', faturamento_anual:'Menos de $100.000', visibilidade_google:'Não apareço', tem_gmb:'Não tenho', usa_instagram:'Sim, uso minha rede pessoal (perfil pessoal)', instagram_handle:'@wagnercapacete', tem_site:'Não tenho site', url_site:null, investimento_mensal:'$0 (não invisto nada)', faz_anuncios:'Nunca fiz / Não sei como fazer', controle_clientes:null, canal_aquisicao:'Não sei / Varia muito', usa_ia:'Sim, uso IA para criar posts, textos ou conteúdo', dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:true, problema_principal:'Rede social', trabalhou_agencia:'Não, essa seria a primeira vez', urgencia:'Estou só conhecendo as opções por enquanto', intencao_avancar:false, intencao_entender:false, intencao_talvez:false, intencao_sem_orcamento:true, intencao_pensar:false, response_type:'completed', start_date:'2026-02-20 22:02:52 UTC', stage_date:null, submit_date:'2026-02-20 22:09:32 UTC', network_id:'7d5b5c1563' },
  { response_id:'njqk1khnw2e2xvc28m9njqk1k4rkt0g0', first_name:'Juliana', last_name:'Sanches Frois', phone:'+12672962636', email:'homainstitute.orlando@gmail.com', empresa:'Homa Institute LLC', tipo_negocio:'Clínica / Saúde (Healthcare)', tempo_negocio:'1 a 3 anos', num_colaboradores:'4 a 10 pessoas', faturamento_anual:'$500.000 a $1.000.000', visibilidade_google:'Sim, apareço com endereço, telefone e avaliações', tem_gmb:'Não tenho', usa_instagram:'Sim, tenho um perfil da empresa', instagram_handle:'homainstitute_', tem_site:'Sim, tenho site ativo', url_site:'Homainstitute USA.com', investimento_mensal:'Mais de $3.000', faz_anuncios:'Sim, invisto apenas no Facebook/Instagram', controle_clientes:'Uso um CRM (sistema de gestão)', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Sim, uso IA para criar posts, textos ou conteúdo', dor_sem_clientes:false, dor_so_brasileiro:true, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:'Qualidade e quantidade', trabalhou_agencia:'Sim, e tive bons resultados', urgencia:'Planejando — Vou investir nos próximos 2-3 meses', intencao_avancar:false, intencao_entender:true, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-02-20 22:02:44 UTC', stage_date:null, submit_date:'2026-02-20 22:08:04 UTC', network_id:'6bfe8d3773' },
  { response_id:'sty6wgmngmkok4drfsty6wgm9pupkocd', first_name:'Karla Andrea', last_name:'Pereira Lima', phone:'+16892210057', email:'drakarlaandrea@hotmail.com', empresa:'Lions Rise Finance', tipo_negocio:'Planejamento Financeiro', tempo_negocio:'Menos de 1 ano', num_colaboradores:'Só eu (sozinho)', faturamento_anual:'Menos de $100.000', visibilidade_google:'Não apareço', tem_gmb:'Não tenho', usa_instagram:'Sim, tenho um perfil da empresa', instagram_handle:'Lionsrisefinance', tem_site:'Estou criando/planejando criar', url_site:'Criando', investimento_mensal:'$300 a $1.000', faz_anuncios:'Nunca fiz / Não sei como fazer', controle_clientes:'Guardo tudo na cabeça / Não tenho controle', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Sim, uso IA para criar posts, textos ou conteúdo', dor_sem_clientes:false, dor_so_brasileiro:true, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:false, problema_principal:'Criação de conteúdo sem precisar de mim', trabalhou_agencia:'Sim, e tive bons resultados', urgencia:'Urgente — Preciso começar agora', intencao_avancar:false, intencao_entender:false, intencao_talvez:true, intencao_sem_orcamento:false, intencao_pensar:true, response_type:'completed', start_date:'2026-02-20 22:02:34 UTC', stage_date:null, submit_date:'2026-02-20 22:07:36 UTC', network_id:'e97a1f42da' },
  { response_id:'ybo9ejg4tba1i8d0ekybo9ejlj27sgvs', first_name:'Marylia', last_name:'Lima', phone:'+19044022955', email:'mqualitycountertops@gmail.com', empresa:'Quality Countertops Granite and Marble', tipo_negocio:'Construção / Reformas (Construction)', tempo_negocio:'+ 10 anos', num_colaboradores:'11 a 20 pessoas', faturamento_anual:'$1.000.000 a $5.000.000', visibilidade_google:'Sim, apareço com endereço, telefone e avaliações', tem_gmb:'Sim, mas não sei mexer direito', usa_instagram:'Sim, tenho um perfil da empresa', instagram_handle:'qualitycountertops_jax', tem_site:'Sim, tenho site ativo', url_site:'https://www.quality-countertops.com/', investimento_mensal:'$0 (não invisto nada)', faz_anuncios:'Nunca fiz / Não sei como fazer', controle_clientes:'Anoto em caderno ou agenda', canal_aquisicao:'Indicação (boca a boca)', usa_ia:'Não uso nada de IA ainda', dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:true, dor_dependencia_op:false, problema_principal:'Postagem', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Alta prioridade — Quero começar nas próximas semanas', intencao_avancar:false, intencao_entender:true, intencao_talvez:false, intencao_sem_orcamento:false, intencao_pensar:false, response_type:'completed', start_date:'2026-02-20 22:02:24 UTC', stage_date:null, submit_date:'2026-02-20 22:08:19 UTC', network_id:'e97a1f42da' },
  { response_id:'533xy0rltt2zgt0it9g533xyqst5g230', first_name:'Fabiano', last_name:'Coelho', phone:'+13213189563', email:'financeiro@vpoexperince.com', empresa:'Vpo experience', tipo_negocio:'Transporte / Turismo', tempo_negocio:'5 a 8 anos', num_colaboradores:'4 a 10 pessoas', faturamento_anual:'$500.000 a $1.000.000', visibilidade_google:'Sim, apareço com endereço, telefone e avaliações', tem_gmb:'Sim, e eu gerencio ele ativamente', usa_instagram:'Sim, tenho um perfil da empresa', instagram_handle:null, tem_site:'Sim, tenho site ativo', url_site:'Www.vpoexperience.com', investimento_mensal:'$300 a $1.000', faz_anuncios:'Sim, invisto apenas no Facebook/Instagram', controle_clientes:'Guardo tudo na cabeça / Não tenho controle', canal_aquisicao:'Redes sociais (Instagram, TikTok)', usa_ia:'Não uso nada de IA ainda', dor_sem_clientes:false, dor_so_brasileiro:false, dor_sem_google:false, dor_sem_mkt:false, dor_anuncio_sem_retorno:false, dor_sem_tempo_redes:false, dor_dependencia_op:true, problema_principal:'Baixo desempenho', trabalhou_agencia:'Sim, mas não valeu a pena', urgencia:'Planejando — Vou investir nos próximos 2-3 meses', intencao_avancar:false, intencao_entender:false, intencao_talvez:false, intencao_sem_orcamento:true, intencao_pensar:false, response_type:'completed', start_date:'2026-02-20 22:02:24 UTC', stage_date:null, submit_date:'2026-02-20 22:08:23 UTC', network_id:'e97a1f42da' },
];

async function run() {
  const client = await pool.connect();
  try {
    // Migration
    await client.query(`
      ALTER TABLE leads
        ADD COLUMN IF NOT EXISTS origem                 TEXT DEFAULT 'brasil',
        ADD COLUMN IF NOT EXISTS dor_so_brasileiro      BOOLEAN DEFAULT FALSE,
        ADD COLUMN IF NOT EXISTS intencao_sem_orcamento BOOLEAN DEFAULT FALSE,
        ADD COLUMN IF NOT EXISTS intencao_pensar        BOOLEAN DEFAULT FALSE
    `);
    await client.query(`UPDATE leads SET origem = 'brasil' WHERE origem IS NULL`);
    console.log('✓ Migration concluída');

    let inserted = 0;
    for (const l of leads) {
      const r = await client.query(`
        INSERT INTO leads (
          response_id, first_name, last_name, phone, email, empresa,
          tipo_negocio, tempo_negocio, num_colaboradores, faturamento_anual,
          visibilidade_google, tem_gmb, usa_instagram, instagram_handle,
          tem_site, url_site, investimento_mensal, faz_anuncios,
          controle_clientes, canal_aquisicao, usa_ia,
          dor_sem_clientes, dor_so_brasileiro, dor_sem_google, dor_sem_mkt,
          dor_anuncio_sem_retorno, dor_sem_tempo_redes, dor_dependencia_op,
          problema_principal, trabalhou_agencia, urgencia,
          intencao_avancar, intencao_entender, intencao_talvez,
          intencao_sem_orcamento, intencao_pensar,
          response_type, start_date, stage_date, submit_date, network_id,
          stage, origem
        ) VALUES (
          $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,
          $17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
          $31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,'nao_iniciado','eua'
        ) ON CONFLICT (response_id) DO NOTHING
      `, [l.response_id,l.first_name,l.last_name,l.phone,l.email,l.empresa,
          l.tipo_negocio,l.tempo_negocio,l.num_colaboradores,l.faturamento_anual,
          l.visibilidade_google,l.tem_gmb,l.usa_instagram,l.instagram_handle,
          l.tem_site,l.url_site,l.investimento_mensal,l.faz_anuncios,
          l.controle_clientes,l.canal_aquisicao,l.usa_ia,
          l.dor_sem_clientes,l.dor_so_brasileiro,l.dor_sem_google,l.dor_sem_mkt,
          l.dor_anuncio_sem_retorno,l.dor_sem_tempo_redes,l.dor_dependencia_op,
          l.problema_principal,l.trabalhou_agencia,l.urgencia,
          l.intencao_avancar,l.intencao_entender,l.intencao_talvez,
          l.intencao_sem_orcamento,l.intencao_pensar,
          l.response_type,l.start_date,l.stage_date,l.submit_date,l.network_id]);
      if (r.rowCount > 0) inserted++;
    }
    console.log('✓ Leads EUA inseridos:', inserted, 'de', leads.length);

    const counts = await client.query('SELECT origem, COUNT(*) as total FROM leads GROUP BY origem ORDER BY origem');
    console.log('\nDistribuição por origem:');
    counts.rows.forEach(r => console.log(' ', r.origem, '->', r.total, 'leads'));
  } finally {
    client.release();
    await pool.end();
  }
}

run().catch(e => { console.error(e.message); process.exit(1); });
